name: ambulance_module
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

flutter_native_splash:
  color: "#F8C1AD"
  background_image: "assets/images/grapesLogo.png"

dependencies:
  basic_utils: ^5.5.1
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2

  plugin_platform_interface:
  dartz: ^0.10.1
  dio: ^4.0.4
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_intl: ^0.0.1
  flutter_native_splash: null
  flutter_polyline_points: ^2.0.0
  flutter_screenutil: ^5.7.0
  flutter_secure_storage: ^7.0.1
  flutter_svg: null
  fluttertoast: ^8.2.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  geolocator: ^10.0.1
  device_info_plus:
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  http_parser: ^4.0.2
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  geocoding: ^2.0.2

  lottie: ^2.6.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.1.1
  streaming_shared_preferences: ^2.0.0
  url_launcher: null
  uuid: 
  webview_flutter: ^2.0.14
  sensors:
  audioplayers: ^5.1.0
  mobile_device_identifier: ^0.0.2


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
